import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

type Props = {
  post_id: string | number
}

const Comments: React.FC<Props> = ({post_id}) => {
  const router = useRouter()

  const [comments, setComments] = useState<{ text: string; username: string }[]>([])

  async function getComments() {
    try {
      const response = await fetch(`/api/comments?postId=${encodeURIComponent(String(post_id))}`)
      if (!response.ok) {
        throw new Error('Failed to load comments')
      }

      const data = await response.json()
      setComments(Array.isArray(data.comments) ? data.comments : [])
    } catch (err) {
      console.log(err)
    }
  }

  useEffect(() => {

    getComments()

  }, [post_id])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div style={{paddingLeft: 50}}>Comments</div>
        {
          comments.map((comment, idx) => (
            <div key={idx} style={{paddingLeft: 50}}>
              <hr></hr>
              <p><a href={`${router.basePath}/profile/${comment.username}`}>@{comment.username}</a></p>
              <p>{comment.text}</p>
              <hr></hr>
            </div>
            
          ))
        }

      </div>

     
  )
}

export default Comments
